### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by jstela** [rddill-IBM/ZeroToBlockchain#10]
Hi Bob, any thoughts why I'm getting this error:
![image](https://user-images.githubusercontent.com/7550712/34630532-9e441772-f253-11e7-8802-3aaddc2066b2.png)

Tried to unistal npm and install again and not working

**Comment by rddill-IBM** [comment]
Yes.  If you look at the read me file fir this chapter, you’ll see Ethan this is expected in chapter 4. It happens because there are “.cto” files in the answers folder as well as in the network /models folder. 
The readme file is here: https://github.com/rddill-IBM/ZeroToBlockchain/blob/master/Chapter04/README.md

**Comment by jstela** [comment]
Thank you.  I renamed the files and now its working

**Comment by mlecjm** [comment]
I faced also the same issue during my experiment. Can you mention which files you renamed that makes it work?
