### ISSUE TITLE
Latest release (1.3.1) repository package test network build and deploy error  

### ISSUE THREAD

**Issue by mlecjm** [rddill-IBM/ZeroToBlockchain#13]
Hello,
Using a clean and fresh installed Ubuntu 16.04.3 system and the latest released (1.3.1) repository, after setup_Ubuntu_Part_1 & 2 have been successfully executed, I got the following results while trying to install npm node and build the test network from the Chapter03 of the cloned tutorial repository.
Cloud you help me to figure out what is wrong and how can I fix it?

![image](https://user-images.githubusercontent.com/20576517/35325515-5247310e-0137-11e8-8d44-d44addb6d996.png)
![image](https://user-images.githubusercontent.com/20576517/35325526-585e2afc-0137-11e8-842e-5ed3f65fe3e1.png)
![image](https://user-images.githubusercontent.com/20576517/35325531-5c349bf2-0137-11e8-956d-a0348bf31600.png)
![image](https://user-images.githubusercontent.com/20576517/35326265-7dcfc0dc-0139-11e8-8088-309800c27275.png)
![image](https://user-images.githubusercontent.com/20576517/35326476-27044b46-013a-11e8-8c5e-979a1b125f0a.png)

**Comment by rddill-IBM** [comment]
There was an error in the start_rest_server.sh file in the 1.3.1 release, which I did not switch over to using cards instead of user ids and passwords. While the correction was in the master path in this repo, it was not in the release. Current version is now 1.3.2 Sorry for the mistake, the error is corrected.
